//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTable
    {
        public string Symbol { get; set; }
        public double LastPrice { get; set; }
        public double Change { get; set; }
        public double Chg { get; set; }
        public string Currency { get; set; }
        public System.DateTime MarketTime { get; set; }
        public double Volume { get; set; }
        public double VolumeAvg { get; set; }
    }
}
