//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyScraper
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockData
    {
        public int Id { get; set; }
        public string Symbol { get; set; }
        public string LastPrice { get; set; }
        public string Change { get; set; }
        public string PChg { get; set; }
        public string Currency { get; set; }
        public string MarketTime { get; set; }
        public string VolumeAvg { get; set; }
    }
}
